### ISSUE TITLE
Support GET requests with optional body.

### ISSUE THREAD

**Issue by victoriahuang1** [dart-lang/http#1057]
Similar to https://github.com/dart-lang/http/pull/439, but for GET requests.

There are some APIs with GET requests that require a body and not query parameters. It's not possible to use these APIs without supporting this.

**Comment by AlokKumarMaurya** [comment]
you want to pass body in the get request , am i correct @victoriahuang1

**Comment by victoriahuang1** [comment]
> you want to pass body in the get request , am i correct @victoriahuang1

yes this is correct

**Comment by AlokKumarMaurya** [comment]
@victoriahuang1  
Actually we can do that but 
In 2014, the [RFC 7231](https://www.rfc-editor.org/rfc/rfc7231#page-24) superseded [HTTP/1.1](https://www.rfc-editor.org/rfc/rfc2616). It added a warning against the use of GET with a body.

Since we have other methods to do the same thing , that's why we don't have the option you are looking for
