### ISSUE TITLE
Closing a request can take an exorbitant amount of time

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/http#1134]
I am using the following code to make an HTTPS call:

```dart
    _httpClient = HttpClient(context: securityContext);
    _httpClient.connectionTimeout = connectionTimeout;

      var request = await _httpClient.postUrl(url);
      request.headers.contentType =
          ContentType('application', 'json', charset: 'utf-8');
      request.contentLength = utf8.encode(body).length;
      request.write(body);

      await request.flush();

      var response = await request.close().timeout(connectionTimeout);

      var data = await _readResponse(response);
```

The call `await request.close()` normally takes just milliseconds, but can sometimes randomly take up to 1.4 seconds. The behavior is sporadic.

I have measured total time spend handling the request on the server, and the delay is definitely not happening on the server. It appears to be happening in the `http` client, during `request.close()`. (Unfortunately because the `http` code uses the old callback-based async convention, it is hard to debug exactly where the problem is happening...)

**Comment by brianquinlan** [comment]
Hi @lukehutch ,

This issue is related to `dart:io`, not `package:http`, so you should file the issue on the [Dart issue tracker](https://github.com/dart-lang/sdk/issues).

Also, since `await request.close()` won't complete until a response is available from the server, couldn't the variation be explained by network or server performance?

Please refile this bug on the [Dart issue tracker](https://github.com/dart-lang/sdk/issues) if you think that the cause is related to Dart.

Thanks!
