### ISSUE TITLE
Add support for http2

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/http#31]
Now that we have https://github.com/dart-lang/http2

**Comment by nex3** [comment]
As in dart-lang/shelf#50, I don't think it makes sense to have this adapter in the main `http` package, giving it a dependency on the experimental `http2` package. I'd rather have `http2` expose its own `http` client, or have a separate `http_http2` package (maybe with a less goofy name) to unify the two.

**Comment by sgjesse** [comment]
The background for this issue is that for normal users of the http package it should transparently select http/2 if the server in question supports it. For normal request/responses where no http/2 specific features are used, the user does not care, but just want the best protocol to be used.

To achieve that http package could somehow a directory of which hosts support http/2 and cache open connections. For each request/response to these hosts just open individual streams on one of these connections.

There are a number of ways to figure out if a host support http/2

1. If HTTPS is used then a secure socket connection can use ALPN to figure that out when the secure connection is established. If that is the case http/2 transport layered on top of it.

2. If HTTP is used a normal HTTP/1.1 connection is made and one can try an upgrade request. If that succeeds the socket can be detached and a http/2 transport layered on top of it.

That way users of the http package automatically get the benefit of http/2 when available.

**Comment by kevmoo** [comment]
What @sgjesse said

**Comment by nex3** [comment]
That seems worth thinking about once the `http2` package is no longer experimental, but since it currently is it doesn't make sense to have a dependency from a widely-used utility package onto it and it *certainly* doesn't make sense to silently switch over the implementation to use it without the user's consent.

Let's create a client that prototypes the behavior you're describing outside of this package. That'll allow us to make sure the concept and API are solid without tying this package to experimental code. Then once `http2` becomes stable, we can look into moving that logic into `http`.

**Comment by davenotik** [comment]
Excited to implement http2 to try and achieve the promised load time boosts: https://goo.gl/AHBmWz

I guess I should wait for a http2 to make its way to Shelf?

**Comment by nex3** [comment]
@davenotik If you're interested in playing around with it, I'd encourage you to make a shelf adapter that uses the `http2` package.

**Comment by wanjm** [comment]
I still request as support for http2, as the single http2 doesn't support negotiation. and there are still bugs but no one take care of it;
https://github.com/dart-lang/http2/issues/80

**Comment by perezd** [comment]
> I'd rather have http2 expose its own http client

Did this ever happen? What's the suggested path forward in 2024?

**Comment by brianquinlan** [comment]
For Android, you can use `package:cronet_http`, which supports HTTP3/QUIC
For iOS, you can use `package:cupertino_http`, which supports HTTP3/QUIC

**Comment by perezd** [comment]
How does one write library code that needs to depend on http2? I was anticipating relying on `http.Client` or a similar `http2.Client` interface; is that not the case?

**Comment by brianquinlan** [comment]
@perezd I'm not sure that I understand your question. Are you looking for a bidirection interface or one that looks like `http.Client`?

**Comment by perezd** [comment]
I guess I'm wondering how I generically depend on the need for an `http2.Client` like I would analogously in a library depend on `http.Client` to allow my end user to decide if they're using cronet or cupertino packages...does that make sense?

**Comment by brianquinlan** [comment]
If you use `package:cronet_http` or `package:cupertino_http` then you will transparently get HTTP3/QUIC through the `http.Client` interface (if the server supports it)
