### ISSUE TITLE
Exception has occurred. _TypeError (type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>')

### ISSUE THREAD

**Issue by greatbaedee** [dart-lang/http#345]
I don't know why I'm receiving this error:
Exception has occurred.
_TypeError (type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>')

I used build_runner for BaseResponse.dart. Then on the page that I want to display the data on, I wrote the following:
List < BaseResponse > pEShippingDetail = [];
  Future loadMessageList() async {
    http.Response response = await http.get('http://www.efwebservice.com/Public/api/ShipmentItems/GetShippingDetails?token=XE9QZEA5ZLRJ64FLO4210&projectid=1010408');
    //await Future.delayed(Duration(seconds: 3));

    String content = response.body;
    List collection = json.decode(content);
    List < BaseResponse > _messages = collection.map((json) => BaseResponse.fromJson(json)).toList();

    setState(() {
      pEShippingDetail = _messages;
    });
  }

  void initState() {
    loadMessageList();
    super.initState();

  }
![Capture](https://user-images.githubusercontent.com/11525976/69188621-7cbeff00-0ae2-11ea-97e0-95bc7b93ae6a.PNG)

**Comment by greatbaedee** [comment]
I am brand new to flutter, I apologize for the inconveniences that I may have cost.

**Comment by natebosch** [comment]
This looks unrelated to the `http` package.

The String in `content` isn't a json representation of a `List`, it is a `Map`. Try printing `content` to see what it looks like before you `json.decode` it. You should see it surrounded with `{}` instead of `[]`. In that case the variable you assign the decoded result to would need to be `Map` rather than a `List`.

You can isolate the problem and take the HTTP request out of the picture by seeing what you get for `content` and hardcoding it in your file while you work on what to do with decoding it.

Closing since this isn't actionable in this repo.
