### ISSUE TITLE
Failed host lookup: 'somedomain.local'

### ISSUE THREAD

**Issue by burtonmiller** [dart-lang/http#346]
Trying to post to a device on the local network from dart http package (via flutter app on android), and always get: Failed host lookup: 'somedomain.local'

Works great from curl and postman on the mac.

Really need this to work for an IoT project where we have a device on the local network that uses .local to show itself as http://somedomain.local.

**Comment by natebosch** [comment]
This isn't something that can be solved in this package. 

This may have something to do with app permissions. The Flutter team is better equipped to help you solve problems with the app config or with emulators.

See https://github.com/flutter/flutter/issues/29688


Closing since this isn't actionable within this repo.
