### ISSUE TITLE
Some device network type took time too long with Wi-fi or network-data

### ISSUE THREAD

**Issue by isagoutama** [dart-lang/http#372]
Sometimes it's took about 10 minutes too load API, but it's work normal on other devices.

**Comment by natebosch** [comment]
This issue is not actionable, and is not related to `package:http` which does not change behavior based on network types.

Stack overflow may be a better place to get help if you are still having issues. If this is specifically within a flutter app the flutter team may have more knowledge about how devices and emulators may behave, or how app permissions impact behavior.
