### ISSUE TITLE
Http request fails while I am using it web support added to existing app

### ISSUE THREAD

**Issue by KenanYusubov** [dart-lang/http#398]
I have added web support to my app.
 And I am trying to run app in chrome localhost using **flutter run -d chrome**, but it returns bad state: no element error to me.

But it works in mobile version.

App is [here](https://github.com/KenanYusubov/Corona-Tracker).

**Comment by iambaljeet** [comment]
Yes facing the same issue only on the Web.
Using: "http: ^0.11.3+16"

**Comment by natebosch** [comment]
This issue doesn't give us anything to investigate. Different behaviors when moving to the web most likely related to something like CORS or similar. Stack overflow might be a better venue to get support, and you might want to look at the browser console for more information about errors.

If you believe this error is caused by a bug specifically in this package please comment with more details about the error and what you think the bug may be. For general help making http requests in a flutter web project please try stack overflow or a flutter help channel.

Closing for now since this is not actionable.
