### ISSUE TITLE
HttpExceptions is not get

### ISSUE THREAD

**Issue by AhmadAbdollah** [dart-lang/http#406]
refer to this questioin :
[this one](https://stackoverflow.com/questions/61299935/flutter-httpexceptions-handling)
HttpExceptions are not throw when status code is not 200 (or OK)

**Comment by miyoyo** [comment]
https://github.com/dart-lang/http/blob/a131e563c09349f624d5421237183a06fb10552d/CHANGELOG.md#0110

**Comment by natebosch** [comment]
If you mean specifically that you see a `ClientException` and not an `HttpException`, that is indeed intentional.

https://pub.dev/documentation/http/latest/http/ClientException-class.html

I don't think this issue is actionable.

**Comment by maks** [comment]
@natebosch I understand it's intentional, but what is the reasoning behind throwing ClientException [here](https://github.com/dart-lang/http/blob/0eb481b4dd3fd2a408b487793155057e87f946b2/lib/src/io_client.dart#L65) ? Because given that [this issue is still open](https://github.com/dart-lang/sdk/issues/30741) and the original stacktrace can't be included with the new Exception, all that happens is we lose the stacktrace of the underlying `HttpException`.

**Comment by maks** [comment]
I've opened [a new issue specifically for the problem](https://github.com/dart-lang/http/issues/498) I'm seeing.

**Comment by natebosch** [comment]
The reasoning is to have a consistent interface that can be caught on the web or on the VM/AOT. It allows other code using `package:http` to also be platform agnostic.

If we let the `HttpExecption` bubble up, only VM users would be able to catch it, and anyone wanting to catch exception in  a platform agnostic library wouldn't be able to. We could potentially look at adding the original `StackTrace` on the exception.

**Comment by maks** [comment]
Thanks @natebosch that does make perfect sense in regards to use outside the VM context.
