### ISSUE TITLE
delete function send an HTTP OPTIONS rather than DELETE request

### ISSUE THREAD

**Issue by lileeei** [dart-lang/http#407]
http version:  0.12.0+4
flutter version:  Flutter 1.17.0 • channel beta

**Comment by natebosch** [comment]
Can you give more complete reproduction instructions here?

There is nothing in this library that would cause anything other than a `DELETE` request.

https://github.com/dart-lang/http/blob/6a699c05dd4620aee62326930373cb2ab1f963de/lib/src/base_client.dart#L111-L112

The bug here is somewhere else. Without more info it's hard to say where.
