### ISSUE TITLE
Problem in get method

### ISSUE THREAD

**Issue by HamzaNb** [dart-lang/http#415]
I can't receive response when using get method in flutter app
This is my pubspec.yaml file 

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

And this is my code

import 'package:http/http.dart';

 Future<void> testUrl() async {
    var url = 'https://jsonplaceholder.typicode.com/posts';
    var response = await http.get(url);
    print('Response status: ${response.statusCode}');
    print('Response body: ${response.body}');

  }

**Comment by natebosch** [comment]
There isn't much info here to go on. Stack Overflow might be a better place to get general help unrelated to bugs in this package.

Since this is flutter my guess is something with permissions. See https://github.com/flutter/website/issues/3592 requesting more documentation about this.

If you have a stack trace or something that indicates a bug in this package we can revisit.
