### ISSUE TITLE
make "http" windows and web(post) supported

### ISSUE THREAD

**Issue by rupamking1** [dart-lang/http#475]
make "http" windows and web(post) supported

**Comment by mavtar-software** [comment]
Please do make http support "flutter web", i am developing Flutter Web + Elastic Search for Client, who want WEB-IOS-Android and can't make it work without HTTP support.

please help me..... I am stuck since last 10 days.

**Comment by rupamking1** [comment]
Use get.
Post not working.

**Comment by mavtar-software** [comment]
can you give me a sample code to call any web rest api from my "flutter web" app ?

I am new in Flutter. I programmer with 8 years experience but in C#.net.

 even reference link would be a great help to me. thank you.

**Comment by rupamking1** [comment]
If you able to fix HTTP POST, then each and every Flutter developer thankful for this. 

`import 'package:flutter/material.dart';
import 'package:http/http.dart';

void main() async => runApp(Test());

class Test extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Safe(
        child: RaisedButton(
          onPressed: () async {
            final res = await post("http://192.168.0.101:3000/postTest", body: {'test': 123});
            print(res.statusCode); // Error 404
          },
        ),
      ),
    );
  }
}
`

**Comment by natebosch** [comment]
This issue is not clear about the problem you encountered. If you are still having trouble, please post a complete minimal reproduction case with a description of the behavior you see and why you think it is wrong.

If this is a problem with networking permissions in a flutter app the flutter team or stack overflow will be better able to provide support.

`POST` requests are supported on all platforms - though permissions or other concerns outside of this package may interfere. You can confirm that a problem is caused by `package:http` specifically by giving a reproduction case that _doesn't_ have the issue when using `dart:io` or `dart:html` directly, and does have the issue when using `package:http`.
