### ISSUE TITLE
Http Post not working on Flutter Web and Windows

### ISSUE THREAD

**Issue by rupamking1** [dart-lang/http#480]
Http Post not working on Flutter Web and Windows.
pls Fix it.

**Comment by parkerleblanc01** [comment]
Please fix this

**Comment by bubnenkoff** [comment]
What's wrong?

**Comment by rupamking1** [comment]
In windows it shows error when I post http request.

**Comment by michaeldwu** [comment]
Everything I've found so far suggests this is a CORS issue, but I can't figure out how to enable CORS on my backend (Firebase/GCP App Engine)

**Comment by parkerleblanc01** [comment]
You're right, it's definitely related to cors. When you make a request with the http package in flutter web the browser first makes an option request on the apps behalf. The backend service responds with the allowed request, the browser checks the option response and either allows the request or throws a cors error. This is where the problem occurs, inside the http package, instead of waiting for the actual response from the request, it just returns the first Options response.

Rough Example (sorry I'm on my phone):
Say you request stock prices for VOO using some example api
http request:
post(example.com/VOO, body: {"token": "foo"})
expected response: {"voo": $326.22}

browser network activity:
request 1: options(example.com)
response 1: headers: {"allowed-origins": "*", "allowed-methods": ["GET", "POST", "PUT"]}, status: 200, body: {}
request 2: post(example.com/VOO, body: {"token": "foo"})
response 2: {"voo": $326.22}

What the http package returns to the program:
headers: {"allowed-origins": "*", "allowed-methods": ["GET", "POST", "PUT"]}, status: 200, body: {}

What the http package should return to the program:
{"voo": $326.22}

Currently the http package has no way of the programmer actually getting the response they want. They just get the meaningless options response meant for the browser.

**Comment by talregev** [comment]
I understand why http post doesn't work on windows on some of the server.
in http that come from dart.io (all application except web), it not add in the header `Content-Length:` also if force all the header to be lowercase, while http header is sensitive case. it not happen in http web.

**Comment by alloza95** [comment]
I found the same problem! Please need to fix it :(

**Comment by natebosch** [comment]
This package does not make 2 requests - CORS issues are a browser level concept. Stack Overflow is a good resource for resolving those issues.

> in http that come from dart.io (all application except web), it not add in the header `Content-Length:` also if force all the header to be lowercase, while http header is sensitive case. it not happen in http web.

This looks like an issue unrelated to this package. See https://github.com/dart-lang/sdk/issues/46599


There are no actionable issues describe here. If you believe there is an issue with the implementation in _this package_ (that is a problem which does not occur when you use `dart:io` or `dart:html` implementations to make http requests directly, but _does_ occur when you use this package) please file a new issue with a specific and concrete description of the problem.

**Comment by talregev** [comment]
> This package does not make 2 requests - CORS issues are a browser level concept. Stack Overflow is a good resource for resolving those issues.
> 
> > in http that come from dart.io (all application except web), it not add in the header `Content-Length:` also if force all the header to be lowercase, while http header is sensitive case. it not happen in http web.
> 
> This looks like an issue unrelated to this package. See [dart-lang/sdk#46599](https://github.com/dart-lang/sdk/issues/46599)
> 
> There are no actionable issues describe here. If you believe there is an issue with the implementation in _this package_ (that is a problem which does not occur when you use `dart:io` or `dart:html` implementations to make http requests directly, but _does_ occur when you use this package) please file a new issue with a specific and concrete description of the problem.

Who can solve it? Please make it open until the other will.

**Comment by natebosch** [comment]
> Who can solve it?

What problem specifically are you hoping to solve?

**Comment by talregev** [comment]
I want when I create an http request it will make an `Content-Length:` Automatic in the header.
Also, that it will not force all the field in the header to be lower case. 
These requirement of http1.
This is too much to ask from this package?

**Comment by talregev** [comment]
If you need to change the implementation of http request inside `dart:io`, fix it there. Until then, leave this issue open and don't ignore and cover the problem.

**Comment by talregev** [comment]
The only way you use http request it with this package. The docs show only this way to use and create http request. 
Please make this issue open and don't ignore the problem!

**Comment by natebosch** [comment]
> Also, that it will not force all the field in the header to be lower case.

I added a new tracking issue for that feature request specifically at https://github.com/dart-lang/http/issues/609

> These requirement of http1.

It's not a requirement I'm aware of. The spec since RFC2616 has been clear that header names are not case sensitive.
https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

Some spec incompliant servers do seem to require specific case sensitive headers which is why added the feature in the SDK and are designing the API to enable that through this package as well.

> I want when I create an http request it will make an `Content-Length:` Automatic in the header.

That should be happening already.

> The only way you use http request it with this package. The docs show only this way to use and create http request.

Docs for the vanilla Dart HTTP requests are at https://api.dart.dev/stable/2.13.4/dart-io/HttpClient-class.html

It's true that this package aims to be the most friendly API for HTTP requests, however it's not the only API and not the one for non-standard use cases.

**Comment by talregev** [comment]
> That should be happening already.
> 
> >

It not happen in dart:io in http. fix it!

**Comment by talregev** [comment]
Until the #609 will resolve. leave this one open.

**Comment by talregev** [comment]
http in `dart:html` preserve http header case and create `Content-Length:` automatic.
Why you don't do the same in `dart:io`? The implementation should be the same. If someone want to do lowercase, and a different api. But the above behavior  (http from dasrt:html) should by default by both packages.

**Comment by talregev** [comment]
And again. Leave this issue open until it fix.

**Comment by talregev** [comment]
Also, if you are going to fix and add `Content-Length:` automatic, make it sensitive case.
