### ISSUE TITLE
Http client stream listen only called when the file is downloading 

### ISSUE THREAD

**Issue by kjawadDeveloper** [dart-lang/http#502]
I want to listen to the progress during the image download. It works well in android and ios but in the web I only get this listen to callback when the image is downloaded.

```
    var _response = await Client().send(Request("GET",  
    Uri.parse("https://upload.wikimedia.org/wikipedia/commons/f/ff/Pizigani_1367_Chart_10MB.jpg")));

    _total = _response.contentLength;


      _response.stream.listen((value) {
            print("received: ${value.length}");
            _bytes.addAll(value);
            _received += value.length;

        setState(() {

            });
      }).onDone(() {
          setState(() {
            // _image = Uint8List.fromList(_bytes);
          });
      });```

**Comment by ditman** [comment]
It seems the `browser_client.dart` is only listening to the `onLoad` event of a request, instead of its [`progress` events](https://api.dart.dev/stable/2.12.2/dart-html/HttpRequestEventTarget/onProgress.html):

* https://github.com/dart-lang/http/blob/master/lib/src/browser_client.dart#L55-L65

This is probably why when `send` is used in the web, the response goes straight from 0 to 100% in only one progress event.

**Comment by natebosch** [comment]
The browser client does not support streaming because it uses `XmlHttpRequest` so no response object becomes available until the entire response is read. No plans in the short term, but we might investigate using `fetch` to support streaming. https://github.com/dart-lang/http/issues/595
