### ISSUE TITLE
In some indeterminate cases there is a wrong Date value in http Response

### ISSUE THREAD

**Issue by illabo** [dart-lang/http#517]
Was advised to forward an issue here. Could you please consider checking https://github.com/flutter/flutter/issues/73924#issue-785713985

The problem occurs sometimes with wrong values of Date headers in response. In such circumstances headers obtained in app even differs from that in Chrome console network pane. 

Further details are in original issue.

**Comment by natebosch** [comment]
Have you verified that this behavior does not happen when you use `dart:html` to make the HTTP requests instead of `package:http`?

This package does not retain state from requests or responses so I don't see how it could cause a bug like this. Something like browser caching sounds more plausible to me.

**Comment by illabo** [comment]
@natebosch Thank you for checking this issue.
I'm sorry I can't verify it. To me it looks like caching issue too. 
Closing the issue for now, will try to investigate if/when it'll re-occur on my machine.
