### ISSUE TITLE
Please bump version to 1.0 when stable

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/http#60]
Pre-1.0 version numbers make it look like the package is not yet ready for use.

**Comment by nex3** [comment]
There's a major breaking change to a much nicer API currently in the works (see for example #56). I don't want to bump the version until that's finished.

**Comment by donny-dont** [comment]
@davidmorgan I've been working with @nex3 to get `http` towards something like `shelf` for making requests. Hoping to get something in people's hands soon.

**Comment by sroddy** [comment]
@nex3 @donny-dont do you have any update on when all this cool new stuff will be put inside a release?
I've been playing with the master branch in the last month and the new API and middleware stuff look very clean and useful. However I don't feel really confident to rely on the master branch of this library for our production apps, I'm not even sure things are 100% working as they are now.
Thanks

**Comment by nex3** [comment]
We're continuing to forge ahead! Hopefully we'll be able to release 2.0 some time this quarter.

**Comment by donny-dont** [comment]
@nex3 @srawlins can we mark any blockers for a release with the updated behavior?

**Comment by nex3** [comment]
As far as I know there are no longer any blockers other than the difficulty of rolling the world onto a new API.

**Comment by donny-dont** [comment]
I thought there was something with multi-map support. Its been awhile.

**Comment by nex3** [comment]
I was hoping to add good cookie support as a bonus to help reward people for migrating, but I've shifted my focus to Sass and I won't have time.

**Comment by donny-dont** [comment]
@nex3 I think there could be a nice http middleware for cookies on the flutter side. So how about update README and address #163 and :shipit: ?

**Comment by mit-mit** [comment]
I would like to get this bumped to 1.0 very soon, cc @nex3 @natebosch @cskau-g @jakemac53 any reason why we are not ready to do that?

**Comment by jakemac53** [comment]
The direction here has changed significantly, I think we could however publish the existing version as 1.x.

The argument against doing that would be the churn it creates throughout the package the ecosystem due to the breaking-change version bump. This is a non-trivial amount of work on a large number of developers, for what is really just an optics change.

I don't have a really strong opinion here, but we should consider the costs/benefits.

**Comment by eseidelGoogle** [comment]
For better or worse, we now have *lots* of users of Flutter, and thus package:http, which likely is going to force stable-like breaking change approaches regardless.

**Comment by natebosch** [comment]
> For better or worse, we now have _lots_ of users of Flutter, and thus package:http, which likely is going to force stable-like breaking change approaches regardless.

The argument against bumping to `1.0.0` now is _not_ because we plan on other unstable breaking changes before going to `1.0.0`, it's because the version bump itself will cause a lot of churn for no end-user benefit other than appearances.

I'd be fine publishing at `1.0.0` today, however I don't know of anyone who is eager to sign up to do the work of publishing new versions of all the other packages that depend on it.
