### ISSUE TITLE
Handshake error in client (OS Error: CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:359))

### ISSUE THREAD

**Issue by maerlynflagg** [dart-lang/http#604]
i got a screenshot from one of the customers. in this screenshot is above issue shown.

`http: ^0.13.1`

first time i saw this. any idea how to solve this? or is it a bug?  

on Google i found only similar CERTIFICATE_VERIFY_FAILED, but not exactly my CERTIFICATE_VERIFY_FAILED.

**Comment by ErcilioMarques** [comment]
facing same issue

**Comment by natebosch** [comment]
This indicates that the SSL cert is invalid. If you want to specifically allow invalid certs you can construct an `HttpClient` from `dart:io` directly instead of an `http.Client`. You could pass it to an `http.IOClient` if you specifically need that interface.

https://api.dart.dev/stable/2.13.4/dart-io/HttpClient/badCertificateCallback.html

Stack overflow is a better resource for future implementation specific questions.
