### ISSUE TITLE
Not reading the data that i pass to the API post

### ISSUE THREAD

**Issue by asfaqahamed** [dart-lang/http#606]
the username i pass to the API is going empty it is not getting the value from the shared preference which I am assigning

Future<String> getStringValuesSF() async {
    SharedPreferences preferences = await SharedPreferences.getInstance();
    String username = preferences.getString('name');
    return username;
  }
   Future<List<Gender>> getgender() async {
    List<Gender> list=[];
    String username="";
    getStringValuesSF().then((value){
        username=value;
        print ("value:"+username);
    });
    print("user:"+username);
    var url = "https://varmalaa.com/api/Demo/gender";
    var response = await http.post(Uri.parse(url),body:{"email":username});
    list = genResponse(response.body);
    return list;
  }
  static List<Gender> genResponse(String responseBody) {
    final parsed = json.decode(responseBody).cast<Map<String, dynamic>>();
    return parsed.map<Gender>((json) => Gender.fromJson(json)).toList();
  }

**Comment by natebosch** [comment]
POST requests with body fields are working in general. The test demonstrating this is https://github.com/dart-lang/http/blob/778174bca2c13becd88ef3353309190b1e8b9479/test/io/http_test.dart#L124-L151

Without further information this issue is not actionable so I'll close it for now. You might find that stack overflow is a better resource for getting help in your specific usage. If you believe there is a bug in this library please add details about the specific ways the request is not correct.
