### ISSUE TITLE
Something is wrong with MultipartRequest

### ISSUE THREAD

**Issue by aleki** [dart-lang/http#62]
Today I tried make a request to https://api.telegram.org with [MultipartRequest](https://www.dartdocs.org/documentation/http/0.11.3%2B9/http/MultipartRequest-class.html), but I did not succeed. Meanwhile, in the postman chrome application it working fine.

What am I doing wrong?

### Postman
![2017-03-03-113540_902x710_scrot](https://cloud.githubusercontent.com/assets/4836709/23543918/9cd2f46c-0005-11e7-8221-05855685e734.png)

### Http package
I tried run this code:
```dart
import 'dart:async';
import 'package:http/http.dart' as http;

Future main() async {
  final url = Uri.parse('https://api.telegram.org/bot123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11/getMe');
  final request = new http.MultipartRequest('POST', url);
  request.fields['Name'] = 'John';
  final response = await request.send();
  print(await response.stream.bytesToString());
}
```
but got the 504 error:
```html
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.10.0</center>
</body>
</html>
```

**Comment by nex3** [comment]
This isn't really enough information for me to diagnose the problem, since the server doesn't explain why it's timing out. It's possible this is a symptom of #61, or possibly a proxy issue. If it's the former, this is a duplicate, and if it's the latter the fix will involve configuring your system somehow.
