### ISSUE TITLE
Web uses OPTIONS method instead of POST

### ISSUE THREAD

**Issue by EmreSURK** [dart-lang/http#667]
I am trying to make a post request, HTTP package sends OPTIONS as the method in the header instead of POST. 

```dart
await http.post(
      Uri.parse('http://localhost:8080/api/login'),
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
      body: jsonEncode(<String, String>{
        'title': "title",
      }),
    );
```

The same request with cUrl works well:
`
curl -X options http://localhost:8080/api/login  -H "Content-Type: application/json" -d '{"title" : "title"}'
`

The same request with the http.Request object works well:

```dart
    final req = Request('POST', Uri.http("localhost:8080", "/api/login"));
    req.body = jsonEncode(body);
    final resp = await req.send();
    final responseStr = await resp.stream.bytesToString();
```

Unfortunately, the Request object does not take headers. 

```
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.0.1 21A559 darwin-arm, locale en-TR)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
[✓] VS Code (version 1.64.2)
[✓] VS Code (version 1.64.1)
[✓] Connected device (1 available)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.```

HTTP package version:  0.13.4
I am using shelf_router in the backend.

Thanks.

**Comment by Carlo-TMC** [comment]
I got this issue when verifying recaptcha token. 

`
var response = await http.post(
          Uri.parse('https://www.google.com/recaptcha/api/siteverify'),
          headers: {
            'Access-Control-Allow-Origin': '*',
          },
          body: <String, String>{
                  'secret': Config.secretKey,
                  'response': Uri.encodeFull(_token)
                },
          encoding: Encoding.getByName("utf-8"),
        );`
        
keep on getting StatusCode 405 - XMLHttpRequest error 

any idea why?

**Comment by hyobbb** [comment]
I am having the same issue

**Comment by tanjunior** [comment]
I am having the same issue too

**Comment by natebosch** [comment]
This is behavior of the browser. We cannot control this from this library or the Dart SDK.

Any time you make a CORS `POST` request with a content-type header that isn't in a narrow allowed list it will first make an `OPTIONS` request before the `POST`.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#:~:text=The%20only%20type/subtype%20combinations%20allowed

> Unfortunately, the Request object does not take headers.

The `Request.header` map is mutable. You can write headers into it after constructing the `Request`.
https://pub.dev/documentation/http/latest/http/BaseRequest/headers.html
Although here the reason you don't see the behavior with the other method is specifically _because_ you haven't set the headers. Once you set the headers you'll need to resolve the CORS behavior on your server.

In the future Stack Overflow is a better venue for getting answer to questions about CORS or browser behavior.

Closing since this issue is not actionable.
