### ISSUE TITLE
Unable to get multiple cookie from get request - http

### ISSUE THREAD

**Issue by msarkrish** [dart-lang/http#901]
I'm calling get request for LDAP authentication, In my application its returning JSESSIONID, but with postman for the same request its getting LtpaToken2 and JSESSIONID(Attached Screenshot for reference).

I'm using [http](https://pub.dev/packages/http) package.

I have 2 questions:

Any one know, it is possible to get 2 cookies with single get request or it is not possible with http package?

Any one know, Whether we can achieve this with flutter?

Thanks in Advance.

Currently I'm initiating 2 request to get 2 tokens, First i'm calling the authenticate url with postUrl method and getting ltpatoken and calling get method with same url and getting jsessionid.

```
httpRequest = await apiService.getUrl(
        uri: Uri.parse(Uri.encodeFull(
            '$host$url?j_username=$username&j_password=$password')),
        duration: Duration(minutes: 10),
      );
      httpClientResponse = await httpRequest?.close();
      if (httpClientResponse?.statusCode == 200) {
        List<Cookie>? cookieList = httpClientResponse?.cookies;
        if (cookieList != null && cookieList.isNotEmpty) {
          print('cookieList');
          print(cookieList.toString());
        }
      }

```

Postman Screenshot
![postman_screenshot](https://user-images.githubusercontent.com/45334931/228265934-9acbd725-f931-49ff-b2c3-350b7b1e38b1.png)

Log Screenshot
![jsession](https://user-images.githubusercontent.com/45334931/228266047-e986184b-fa09-43a0-9ed0-518caa3d60ab.png)

**Comment by alex-james-dev** [comment]
Hi Krishnakumar,

I'm new to the dart-lang project, but I would like to try to help.

> Any one know, it is possible to get 2 cookies with single get request or it is not possible with http package?

I believe it is possible to have multiple cookies in the [header](https://pub.dev/documentation/http/latest/http/BaseResponse/headers.html) of a [response](https://pub.dev/documentation/http/latest/http/Response-class.html) from a [get](https://pub.dev/documentation/http/latest/http/Client/get.html) request using [package:http](https://pub.dev/documentation/http/latest/http/http-library.html).

> I'm using [http](https://pub.dev/packages/http) package.

Looking at your code sample, I think you might actually be using [dart:io](https://api.dart.dev/stable/2.19.6/dart-io/dart-io-library.html) for the http requests and not [package:http](https://pub.dev/documentation/http/latest/http/http-library.html). 

I think this because:

> ```
> httpClientResponse = await httpRequest?.close();
> ```
[package:http Request](https://pub.dev/documentation/http/latest/http/Request-class.html#instance-methods) doesn't have a close() method but [dart:io HttpClientRequest](https://api.dart.dev/stable/2.19.6/dart-io/HttpClientRequest/close.html) does.

> ```
> List<Cookie>? cookieList = httpClientResponse?.cookies;
> ```

[package:http Response](https://pub.dev/documentation/http/latest/http/Response-class.html#instance-properties) doesn't have a cookies property but [dart:io HttpClientResponse](https://api.dart.dev/stable/2.19.6/dart-io/HttpClientResponse/cookies.html) does.

It is recommended in the docs to use package:http instead of dart:io for networking. But in this case both dart:io and package:http support multiple cookies in the response header.

### Reproducing the bug
I was unable to reproduce this bug on Dart 2.19.5 (stable). I made a get request to github.com using dart:io and received 3 cookies in the response header. 

Code:

```
var client = HttpClient();
try {
  HttpClientRequest request = await client.getUrl(Uri.https('github.com'));
  HttpClientResponse response = await request.close();
  print("Number of cookies: ${response.cookies.length}");
  print("Cookies: ${response.cookies.toString()}");
  response.drain();
} finally {
  client.close();
}
```

Output:

``` 
Number of cookies: 3
```

### Questions

1. Does your issue occur with any url? Have you tried other urls? 
2. Can you share a url which is having this issue, to see if we can reproduce it?
3. What version of Dart/Flutter are you using?
4. What is the output of the httpClientResponse?.headers property? Does it include the missing headers?

Hope to hear from you soon,
Alex

**Comment by msarkrish** [comment]
Thank you @alex-james-dev for your detailed explanation, Actually I came to close this issue. Because After created issue, Today only I have tried with different urls and I found that we can get multiple cookies in the response. I think it's a issue with our backend solution. 

I have only one question @alex-james-dev  it's not regarding this issue, I will close this issue. But my question is,
With the below code I can able to get cookie but not able to get response body directly. But I can get it with transform method from stream. 
**My question is why any direct getter is not available here for response body with response object?**

```
HttpClientRequest request = await client.getUrl(Uri.https('github.com'));
HttpClientResponse response = await request.close();
```

With the below code I can able to get response body but not able to get cookie directly. But I can able to get cookie from response headers. 
**My question is why any direct getter is not available here for cookies with response object?**

```
Response response=await http.get(Uri.parse('https://catfact.ninja/fact'));
```
