### ISSUE TITLE
Connection Timeout Exception on mobile network

### ISSUE THREAD

**Issue by aliaafreen** [dart-lang/http#939]
I am facing an issue related to http request from flutter app to the server. 
I have got connection timeout exception(110) on certain Android devices on mobile network but on wifi it works fine. 
I have been facing this issue for last 3 months, I have tried all the solutions available  related to this but I did not get a proper solution. 
I have checked it with http, retry and dio packages, but  all of them have same issue.  And all another apps in my mobile phone that need internet connection works properly but my flutter app does not.
Will anyone got any solution for it or help me to solve it?

  dio: ^5.0.3
  http: ^0.13.5
  retry: ^3.1.1

flutter - 3.7.7 / 3.3.2/ 2.10.4 (I have tried on three of them)

**Comment by guy-evdev** [comment]
I can confirm the same bug using an Asus X00GD device

Using the http package and flutter 3.10.5

**Comment by natebosch** [comment]
This looks unrelated to `package:http`. You will likely find better support on the flutter repo or on stack overflow. This could be a permissions issue.
https://docs.flutter.dev/data-and-backend/networking

Closing here since there are not changes we can make in `package:http` to influence networking permissions on mobile devices.
