### ISSUE TITLE
Failure HTTP Status codes are not returned when targeting the Web

### ISSUE THREAD

**Issue by wkok** [dart-lang/http#989]
When the server returns any status code other than success for example `401 Unauthorized`, `404 Not found` etc. then the behaviour between platforms are inconsistent:

- Desktop/Mobile: `get` or `post` returns the `statusCode` `401` as expected
- Web: `get` or `post` throws a `ClientException` with the message _XMLHttpRequest error_

This makes it impossible to respond to the various HTTP response status codes when targeting multiple platforms

**Comment by SamJakob** [comment]
Duplicate of #927?

**Comment by wkok** [comment]
> Duplicate of #927?

Somewhat related but not entirely. #927 addresses network level errors that throws exceptions in both native and web.

This issue addresses failed status code responses (application level) sent from the server, where in native a response containing the status code is returned to the calling code, but in web an exception is thrown containing no detail.

**Comment by SamJakob** [comment]
I see. I think I was suggesting this as a potential duplicate in the anticipation of a solution that exposes underlying errors (because in either case they were different) but as that defeats the purpose the package (of exposing a uniform cross platform API) it would, of course, be ideal to just set the status code if possible.

Are you sure the status code is returned in the browser for an ordinary XHR? MDN seems to suggest in the event of an error the status code is set to 0, so it might not be possible to read.

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/status

**Comment by wkok** [comment]
Yes I can confirm XMLHttpRequest returns the status code, see the below example based on their documentation:

![image](https://github.com/dart-lang/http/assets/5214136/a046a5a4-2df0-485a-9298-a854732c83f1)

**Comment by wkok** [comment]
This ended up being related to [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). When the browser blocks the request due to [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), `XMLHttpRequest` returns status code 0 and an empty body, which gets resolved by the dart http library into a `ClientException` with message _XMLHttpRequest error_

After resolving the CORS issue in my server, the failed status codes got reported as expected via the dart http library.
